// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102155953_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Core.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CoursePar")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CourseRating")
                        .HasPrecision(4, 1)
                        .HasColumnType("REAL");

                    b.Property<double>("CourseSlope")
                        .HasColumnType("REAL");

                    b.Property<int>("NumHoles")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_CourseId");

                    b.ToTable("Course", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseSlope", "[CourseSlope] BETWEEN 55 AND 155");
                        });
                });

            modelBuilder.Entity("Core.Models.Golfer", b =>
                {
                    b.Property<int>("GolferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateLastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("FirstName || ' ' || LastName");

                    b.Property<double>("Handicap")
                        .HasPrecision(4, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("GolferId");

                    b.HasIndex("GolferId")
                        .HasDatabaseName("IX_GolferId");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_GolferName");

                    b.ToTable("Golfer", null, t =>
                        {
                            t.HasCheckConstraint("CK_Handicap", "[Handicap] <= '54'");
                        });
                });

            modelBuilder.Entity("Core.Models.GolferLeagueJunction", b =>
                {
                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GolferId", "LeagueId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("GolferId", "LeagueId")
                        .HasDatabaseName("IX_GolferLeague");

                    b.ToTable("GolferLeagueJunction", (string)null);
                });

            modelBuilder.Entity("Core.Models.GolferMatchupJunction", b =>
                {
                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("GolferId", "MatchupId");

                    b.HasIndex("MatchupId");

                    b.HasIndex("GolferId", "MatchupId")
                        .HasDatabaseName("IX_GolferMatchup");

                    b.ToTable("GolferMatchupJunction", (string)null);
                });

            modelBuilder.Entity("Core.Models.GolferTeamJunction", b =>
                {
                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GolferId", "TeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GolferId", "TeamId")
                        .HasDatabaseName("IX_GolferTeam");

                    b.ToTable("GolferTeamJunction", (string)null);
                });

            modelBuilder.Entity("Core.Models.Hole", b =>
                {
                    b.Property<int>("HoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Handicap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Par")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoleId");

                    b.HasIndex("HoleId")
                        .HasDatabaseName("IX_HoleId");

                    b.HasIndex("CourseId", "HoleId")
                        .HasDatabaseName("IX_CourseHole");

                    b.ToTable("Hole", null, t =>
                        {
                            t.HasCheckConstraint("CK_Distance", "[Distance] > 0");

                            t.HasCheckConstraint("CK_Handicap", "[Handicap] > 0");

                            t.HasCheckConstraint("CK_HoleNum", "[HoleNum] > 0");

                            t.HasCheckConstraint("CK_Par", "[Par] > 0");
                        });
                });

            modelBuilder.Entity("Core.Models.HoleScore", b =>
                {
                    b.Property<int>("HoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatePlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GrossScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoleId", "GolferId", "RoundId");

                    b.HasIndex("GolferId");

                    b.HasIndex("RoundId");

                    b.HasIndex("HoleId", "GolferId", "RoundId")
                        .HasDatabaseName("IX_HoleGolferRound");

                    b.ToTable("HoleScore", null, t =>
                        {
                            t.HasCheckConstraint("CK_GrossScore", "[GrossScore] > 0");

                            t.HasCheckConstraint("CK_NetScore", "[NetScore] > 0");
                        });
                });

            modelBuilder.Entity("Core.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeagueId");

                    b.HasIndex("CourseId");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_LeagueId");

                    b.HasIndex("LeagueSettingsId");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("Core.Models.LeagueSetting", b =>
                {
                    b.Property<int>("LeagueSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueSettingsName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayDate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoringRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeagueSettingsId");

                    b.HasIndex("LeagueSettingsId")
                        .HasDatabaseName("IX_LeagueSettingsId");

                    b.HasIndex("ScoringRuleId");

                    b.ToTable("LeagueSettings", (string)null);
                });

            modelBuilder.Entity("Core.Models.Matchup", b =>
                {
                    b.Property<int>("MatchupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("MatchupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchupId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("MatchupId")
                        .HasDatabaseName("IX_MatchupId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("MatchupId", "LeagueId")
                        .HasDatabaseName("IX_MatchupIdLeagueId");

                    b.HasIndex("MatchupId", "SeasonId")
                        .HasDatabaseName("IX_MatchupIdSeasonId");

                    b.ToTable("Matchup", (string)null);
                });

            modelBuilder.Entity("Core.Models.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveSubstitute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrossTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("NetTotal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScoreDifferential")
                        .HasColumnType("REAL");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundId");

                    b.HasIndex("CourseId");

                    b.HasIndex("GolferId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("IX_RoundId");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchupId", "GolferId")
                        .HasDatabaseName("IX_MatchupIdGolferId");

                    b.ToTable("Round", (string)null);
                });

            modelBuilder.Entity("Core.Models.ScoringRule", b =>
                {
                    b.Property<int>("ScoringRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ScoringRuleId");

                    b.HasIndex("ScoringRuleId")
                        .HasDatabaseName("IX_ScoringRuleId");

                    b.ToTable("ScoringRule", (string)null);
                });

            modelBuilder.Entity("Core.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_SeasonId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("Core.Models.Substitute", b =>
                {
                    b.Property<int>("GolferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalGolferId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GolferId", "TeamId", "MatchupId");

                    b.HasIndex("MatchupId")
                        .HasDatabaseName("IX_Matchup");

                    b.HasIndex("OriginalGolferId")
                        .HasDatabaseName("IX_OriginalGolfer");

                    b.HasIndex("TeamId");

                    b.HasIndex("GolferId", "TeamId", "MatchupId")
                        .HasDatabaseName("IX_GolferTeamMatchup");

                    b.ToTable("Substitute", (string)null);
                });

            modelBuilder.Entity("Core.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_TeamId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("Core.Models.TeamMatchupJunction", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamMatchupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "MatchupId");

                    b.HasIndex("MatchupId");

                    b.HasIndex("TeamId", "MatchupId")
                        .HasDatabaseName("IX_TeamIdMatchupId");

                    b.ToTable("TeamMatchupJunction", null, t =>
                        {
                            t.HasCheckConstraint("CK_PointsAwarded", "[PointsAwarded] >= 0");
                        });
                });

            modelBuilder.Entity("Core.Models.GolferLeagueJunction", b =>
                {
                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany("GolferLeagueJunctions")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.League", "League")
                        .WithMany("GolferLeagueJunctions")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Golfer");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Core.Models.GolferMatchupJunction", b =>
                {
                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany("GolferMatchupJunctions")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Matchup", "Matchup")
                        .WithMany("GolferMatchupJunctions")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Golfer");

                    b.Navigation("Matchup");
                });

            modelBuilder.Entity("Core.Models.GolferTeamJunction", b =>
                {
                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany("GolferTeamJunctions")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Team", "Team")
                        .WithMany("GolferTeamJunctions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Golfer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Models.Hole", b =>
                {
                    b.HasOne("Core.Models.Course", "Course")
                        .WithMany("Holes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Models.HoleScore", b =>
                {
                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany("HoleScores")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Hole", "Hole")
                        .WithMany("HoleScores")
                        .HasForeignKey("HoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Round", "Round")
                        .WithMany("HoleScores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Golfer");

                    b.Navigation("Hole");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Core.Models.League", b =>
                {
                    b.HasOne("Core.Models.Course", "Course")
                        .WithMany("Leagues")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.LeagueSetting", "LeagueSettings")
                        .WithMany("Leagues")
                        .HasForeignKey("LeagueSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LeagueSettings");
                });

            modelBuilder.Entity("Core.Models.LeagueSetting", b =>
                {
                    b.HasOne("Core.Models.ScoringRule", "ScoringRule")
                        .WithMany("LeagueSettings")
                        .HasForeignKey("ScoringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringRule");
                });

            modelBuilder.Entity("Core.Models.Matchup", b =>
                {
                    b.HasOne("Core.Models.League", "League")
                        .WithMany("Matchups")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Season", "Season")
                        .WithMany("Matchups")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Core.Models.Round", b =>
                {
                    b.HasOne("Core.Models.Course", "Course")
                        .WithMany("Rounds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany("Rounds")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.League", "League")
                        .WithMany("Rounds")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Matchup", "Matchup")
                        .WithMany("Rounds")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Team", "Team")
                        .WithMany("Rounds")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Golfer");

                    b.Navigation("League");

                    b.Navigation("Matchup");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Models.Season", b =>
                {
                    b.HasOne("Core.Models.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Core.Models.Substitute", b =>
                {
                    b.HasOne("Core.Models.Golfer", "Golfer")
                        .WithMany()
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Matchup", "Matchup")
                        .WithMany("Substitutes")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Golfer", "OriginalGolfer")
                        .WithMany()
                        .HasForeignKey("OriginalGolferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Team", "Team")
                        .WithMany("Substitutes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Golfer");

                    b.Navigation("Matchup");

                    b.Navigation("OriginalGolfer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Models.Team", b =>
                {
                    b.HasOne("Core.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Core.Models.TeamMatchupJunction", b =>
                {
                    b.HasOne("Core.Models.Matchup", "Matchup")
                        .WithMany("TeamMatchupJunctions")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Team", "Team")
                        .WithMany("TeamMatchupJunctions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matchup");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Models.Course", b =>
                {
                    b.Navigation("Holes");

                    b.Navigation("Leagues");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Core.Models.Golfer", b =>
                {
                    b.Navigation("GolferLeagueJunctions");

                    b.Navigation("GolferMatchupJunctions");

                    b.Navigation("GolferTeamJunctions");

                    b.Navigation("HoleScores");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Core.Models.Hole", b =>
                {
                    b.Navigation("HoleScores");
                });

            modelBuilder.Entity("Core.Models.League", b =>
                {
                    b.Navigation("GolferLeagueJunctions");

                    b.Navigation("Matchups");

                    b.Navigation("Rounds");

                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Core.Models.LeagueSetting", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("Core.Models.Matchup", b =>
                {
                    b.Navigation("GolferMatchupJunctions");

                    b.Navigation("Rounds");

                    b.Navigation("Substitutes");

                    b.Navigation("TeamMatchupJunctions");
                });

            modelBuilder.Entity("Core.Models.Round", b =>
                {
                    b.Navigation("HoleScores");
                });

            modelBuilder.Entity("Core.Models.ScoringRule", b =>
                {
                    b.Navigation("LeagueSettings");
                });

            modelBuilder.Entity("Core.Models.Season", b =>
                {
                    b.Navigation("Matchups");
                });

            modelBuilder.Entity("Core.Models.Team", b =>
                {
                    b.Navigation("GolferTeamJunctions");

                    b.Navigation("Rounds");

                    b.Navigation("Substitutes");

                    b.Navigation("TeamMatchupJunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
